//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerWidgetMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CustomerWidgetEntities : DbContext
    {
        public CustomerWidgetEntities()
            : base("name=CustomerWidgetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerCar> CustomerCars { get; set; }
        public virtual DbSet<Dealer> Dealers { get; set; }
        public virtual DbSet<DealerServicePackage> DealerServicePackages { get; set; }
        public virtual DbSet<ServicePackage> ServicePackages { get; set; }
        public virtual DbSet<Slot> Slots { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
