//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerWidgetMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Appointments = new HashSet<Appointment>();
            this.CustomerCars = new HashSet<CustomerCar>();
        }

        public int CustomerId { get; set; }
      //  [Required(ErrorMessage = "FirstName is Required!")]
        public string FirstName { get; set; }
       // [Required(ErrorMessage = "LastName is Required!")]
        public string LastName { get; set; }
       // [Required(ErrorMessage = "Email is Required!")]
        public string Email { get; set; }
       // [DataType("Password")]
       // [Required(ErrorMessage = "Password is Required!")]
        public string Password { get; set; }
       // [DataType("Password")]
        //[Compare("Password")]
       // [Required(ErrorMessage = "ConfirmPassword is Required!")]
        public string ConfirmPassword { get; set; }
       // [Required(ErrorMessage = "Address is Required!")]
        public string Address { get; set; }
        //[Required(ErrorMessage = "Contact is Required!")]
        public long ContactNo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCar> CustomerCars { get; set; }
    }
}
