//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerWidgetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slot
    {
        public int DealerId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan SlotTime { get; set; }
        public int SlotAvailable { get; set; }
    
        public virtual Dealer Dealer { get; set; }
    }
}
