//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleController.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerServicePackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DealerServicePackage()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int DealerServiceId { get; set; }
        public int ServiceId { get; set; }
        public int DealerId { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Dealer Dealer { get; set; }
        public virtual ServicePackage ServicePackage { get; set; }
    }
}
